# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('commentLike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmanager.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=100)),
                ('borrower', models.CharField(max_length=100)),
                ('sum', models.CharField(max_length=9)),
                ('notes', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmanager.Loan')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmanager.Loan'),
        ),
    ]
