# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0003_auto_20161007_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
