# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0003_commentlike_eventlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
