# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0004_auto_20161009_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
