# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0004_event_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='added',
        ),
    ]
