# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0005_auto_20161009_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='isUserVoted',
            field=models.BooleanField(default=False),
        ),
    ]
