# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0006_loan_isuservoted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logInfo', models.CharField(max_length=200)),
            ],
        ),
    ]
