# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0009_loan_isprivateloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='isLoanReturned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='isPrivate',
            field=models.BooleanField(default=True),
        ),
    ]
