# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0010_auto_20161016_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='logInfo',
        ),
        migrations.AddField(
            model_name='log',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
