# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0011_auto_20161016_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='borrower',
            field=models.CharField(default='', max_length=100),
        ),
    ]
