# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0013_auto_20161016_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='isPrivate',
        ),
        migrations.AddField(
            model_name='log',
            name='isLoanLended',
            field=models.BooleanField(default=False),
        ),
    ]
