# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0014_auto_20161030_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='sum',
            field=models.FloatField(default=0),
        ),
    ]
