# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0015_auto_20161101_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
